# Generated by Django 4.0.2 on 2022-06-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='TYPE',
            field=models.CharField(choices=[('Ad', 'Ad'), ('News', 'News')], default='Ad', max_length=50, null=True),
        ),
    ]
