# Generated by Django 4.0.2 on 2022-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_ad_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ap_name', models.CharField(max_length=50)),
                ('adddress', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('zip', models.IntegerField(default=0)),
            ],
        ),
    ]
