# Generated by Django 4.0.2 on 2022-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applyedfor',
            field=models.CharField(default=21, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='cnic',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
