# Generated by Django 4.0.2 on 2022-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applicant_applyedfor_applicant_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applyedfor',
            field=models.CharField(max_length=5000),
        ),
    ]
